// Automatically generated - do not modify!

@file:Suppress(
    "NON_EXTERNAL_DECLARATION_IN_INAPPROPRIATE_FILE",
    "NON_ABSTRACT_MEMBER_OF_EXTERNAL_INTERFACE",
    "WRONG_MODIFIER_CONTAINING_DECLARATION",
    "WRONG_EXTERNAL_DECLARATION",
)

@file:JsModule("yfiles")

package yfiles.orthogonal

import yfiles.lang.EnumMetadata
import yfiles.lang.YEnum

/**
 * @see [OrthogonalLayout.treeStyle]
 * @see <a href="https://docs.yworks.com/yfileshtml/#/api/TreeLayoutStyle">Online Documentation</a>
 */
external sealed class TreeLayoutStyle: YEnum<TreeLayoutStyle> {
   companion object: EnumMetadata<TreeLayoutStyle> {
       /**
 * A tree layout style that defines that subtrees should not be handled specifically.
 * 
 * Value - `0`
 * @see [OrthogonalLayout.treeStyle]
 * @see <a href="https://docs.yworks.com/yfileshtml/#/api/TreeLayoutStyle%23NONE">Online Documentation</a>
 */
val NONE: TreeLayoutStyle

/**
 * A tree layout style that arranges subtrees in a layered tree fashion with grouped edge routes, generated by a [DefaultNodePlacer][yfiles.tree.DefaultNodePlacer] with routing style [RoutingStyle.FORK][yfiles.tree.RoutingStyle.FORK] and alignment setting [RootAlignment.CENTER][yfiles.tree.RootAlignment.CENTER].
 * 
 * Value - `1`
 * @see [OrthogonalLayout.treeStyle]
 * @see <a href="https://docs.yworks.com/yfileshtml/#/api/TreeLayoutStyle%23DEFAULT">Online Documentation</a>
 */
val DEFAULT: TreeLayoutStyle

/**
 * A tree layout style that arranges subtrees in a layered tree fashion with grouped edge routes and integrates the tree elements into the orthogonal layout framework.
 * 
 * Value - `2`
 * @see [OrthogonalLayout.treeStyle]
 * @see <a href="https://docs.yworks.com/yfileshtml/#/api/TreeLayoutStyle%23INTEGRATED">Online Documentation</a>
 */
val INTEGRATED: TreeLayoutStyle

/**
 * A tree layout style that aims to create maximally compact layouts for the subtrees by using the [CompactNodePlacer][yfiles.tree.CompactNodePlacer] for the tree layout algorithm.
 * 
 * Value - `3`
 * @see [OrthogonalLayout.treeStyle]
 * @see <a href="https://docs.yworks.com/yfileshtml/#/api/TreeLayoutStyle%23COMPACT">Online Documentation</a>
 */
val COMPACT: TreeLayoutStyle

/**
 * A tree layout style that yields tree layouts with an aspect ratio close to `1:1` that are generated by [AspectRatioNodePlacer][yfiles.tree.AspectRatioNodePlacer].
 * 
 * Value - `4`
 * @see [OrthogonalLayout.treeStyle]
 * @see <a href="https://docs.yworks.com/yfileshtml/#/api/TreeLayoutStyle%23ASPECT_RATIO">Online Documentation</a>
 */
val ASPECT_RATIO: TreeLayoutStyle
   }
}
