// Automatically generated - do not modify!

@file:Suppress(
    "NON_EXTERNAL_DECLARATION_IN_INAPPROPRIATE_FILE",
    "NON_ABSTRACT_MEMBER_OF_EXTERNAL_INTERFACE",
    "WRONG_MODIFIER_CONTAINING_DECLARATION",
    "WRONG_EXTERNAL_DECLARATION",
)

package yfiles.lang

/**
 * Encapsulates a method that has no parameters and does not return a value.
 */
typealias Action = () -> Unit

/**
 * Encapsulates a method that has a single parameter and does not return a value.
 * @param [T] The type of the parameter of the method that this delegate encapsulates.
 * @param [obj] The parameter of the method that this delegate encapsulates.
 */
typealias Action1<T> = (obj: T) -> Unit

/**
 * Encapsulates a method that has two parameters and does not return a value.
 * @param [T1] The type of the first parameter of the method that this delegate encapsulates.
 * @param [T2] The type of the second parameter of the method that this delegate encapsulates.
 * @param [arg1] The first parameter of the method that this delegate encapsulates.
 * @param [arg2] The second parameter of the method that this delegate encapsulates.
 */
typealias Action2<T1, T2> = (arg1: T1,
arg2: T2) -> Unit

/**
 * Represents the method that will handle an event that has no event data.
 * @param [sender] The source of the event.
 * @param [event] An object that contains no event data.
 */
typealias EventHandler = (sender: IEventDispatcher,
event: EventArgs) -> Unit

/**
 * Represents the method that will handle an event when the event provides data.
 * @param [TEventArgs] The type of the event data generated by the event.
 * @param [sender] The source of the event.
 * @param [event] An object that contains the event data.
 */
typealias EventHandler1<TEventArgs> = (sender: IEventDispatcher,
event: TEventArgs) -> Unit

/**
 * Encapsulates a method that has one parameters and returns a value of the type specified by the `TResult` parameter.
 * @param [T1] The type of the parameter of the method that this delegate encapsulates.
 * @param [TResult] The type of the return value of the method that this delegate encapsulates.
 * @param [arg] The parameter of the method that this delegate encapsulates.
 * @return The return value of the method that this delegate encapsulates.
 */
typealias Func2<T1, TResult> = (arg: T1) -> TResult

/**
 * Encapsulates a method that has two parameters and returns a value of the type specified by the `TResult` parameter.
 * @param [T1] The type of the first parameter of the method that this delegate encapsulates.
 * @param [T2] The type of the second parameter of the method that this delegate encapsulates.
 * @param [TResult] The type of the return value of the method that this delegate encapsulates.
 * @param [arg1] The first parameter of the method that this delegate encapsulates.
 * @param [arg2] The second parameter of the method that this delegate encapsulates.
 * @return The return value of the method that this delegate encapsulates.
 */
typealias Func3<T1, T2, TResult> = (arg1: T1,
arg2: T2) -> TResult

/**
 * Represents the method that defines a set of criteria and determines whether the specified object meets those criteria.
 * @param [T] The type of the object to compare.
 * @param [obj] The object to compare against the criteria defined within the method represented by this delegate.
 * @return `true` if obj meets the criteria defined within the method represented by this delegate; otherwise, `false`.
 */
typealias Predicate<T> = (obj: T) -> Boolean

/**
 * Defines the handler for a [IPropertyObservable.PropertyChanged] event.
 * @param [sender] The object which dispatched the event.
 * @param [event] The arguments which define the change.
 */
typealias PropertyChangedEventHandler = (sender: IEventDispatcher,
event: PropertyChangedEventArgs) -> Unit
